### PR TITLE
add Mocha

### PR DESCRIPTION
**Pull request by DanielRuf**
The requirements for accepting a new project are simple:

1. The pull request follows the formatting in use already. Please keep the list alphabetized.

2. The project must have at least 100 stars (if on Github). If it's not on Github, I'll use my best judgment as to whether it's worth including.

3. There must be a way to validate the project is open to new maintainers, whether that's an open issue, a notice, it looks like it's been abandoned, or you are the lead yourself. If it's not obvious, leave a comment on the pull request so I can verify.

4. Most projects are open to new contributors at all times. Please only post if the project is looking for a new lead maintainer, suggesting the current maintainer would like to deprioritize or move on.

### CODE REVIEW

**Comment by pickhardt** [comment]
Is Mocha looking for new lead maintainer(s) or just more contributors?

**Comment by DanielRuf** [comment]
Summoning @boneskull ✨

**Comment by DanielRuf** [comment]
Bump.

**Comment by pickhardt** [comment]
I want to keep this as a list of projects looking for new lead maintainers, not just projects looking for contributors. Most projects are always looking for contributors, but only some are looking for new lead(s).

**Comment by DanielRuf** [comment]
The bump was meant for @boneskull ;-)

**Comment by pickhardt** [comment]
Daniel, what's your relationship to the Mocha project? Did you add it because you know it's looking for a new maintainer or because you think it could use one?

**Comment by DanielRuf** [comment]
See https://github.com/mochajs/mocha/issues/3191

**Pull request closed without merging**
