### PR TITLE
Don't shout and use Shields.io directly

### PR DESCRIPTION
**Pull request by olivierlacan**
Of course it's up to you whether you want to make this badge shouty, 
but I don't think it's necessary. 😃 

Example: 
Phew, calm down buddy...
It's always better without shouting

More importantly I'd recommend using the Shields API instead of saving the SVG 
output to your own server. This may end up being hit a lot and we've optimized 
Shields to get hammered by a lot of requests and do the right thing with asset 
caching as much as possible. @espadrine can give you more details if you want.

### CODE REVIEW

**Comment by pickhardt** [comment]
Doesn't Github cache the image anyway? It looks like they do to me.

As for the all caps, I'm pretty indifferent to all caps vs not. If I were to change it to not use all caps, I'd prefer to at least capitalize the words: Maintainers Wanted.

**Comment by olivierlacan** [comment]
Yes, GitHub caches the image. But I believe this cache is regularly updated. We've had several issues for this reason. Can you guarantee that your domain will be accessible in the long-term for GitHub to be able to cache the image in the first place? Again, it's up to you. Shields exists for a reason. 😉 

We've [established a standard](https://github.com/badges/shields/blob/master/spec/SPECIFICATION.md) over the past three years with thousands of open source projects. We use lower cased keys and values because that's what they are. There's no reason to capitalize or titlecase them. You'd be breaking a convention used pretty much everywhere so the badge would clash with others.

Just an example from the Twitter gem: 
image

That said you could justify breaking with conventions because you want to draw attention. I'd argue that the red color of the badge already draws enough attention to itself.

**Comment by pickhardt** [comment]
I merged. What does line 52 do? `[badge]: https://img.shields.io/badge/maintainers-wanted-red.svg`

**Comment by olivierlacan** [comment]
You can remove it. I originally made a reference link to re-use around the README and avoid repeating the same URL but I later noticed that you were using one of them as an example to copy.

**Comment by olivierlacan** [comment]
You can make a reference to a footnote-style URL like this:

```markdown
This is a link[linkname].

Other text.

[linkname]: http://example.com
```

**Pull request merged**
